#!/bin/bash

# http://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -o nounset -o errexit -o pipefail

# POST as application/javascript with curl
# https://curl.haxx.se/docs/manpage.html

curl https://echo.vbarbarosh.com -H Content-Type:application/javascript \
    --data-binary @- << 'EOF'
module.exports = function () {
    console.log('hello');
};
EOF

# HTTP/1.1 POST /
# 
# Host: echo.vbarbarosh.com
# User-Agent: curl/7.58.0
# Content-Type: application/javascript
# Content-Length: 60
# 
# module.exports = function () {
#     console.log('hello');
# };
