#!/bin/bash

# http://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -o nounset -o errexit -o pipefail

# How to add prefixes to css
#
# usage
# $ cat a.css | ./css_autoprefixer > out.css
#
# before begin
# $ npm install -g postcss-cli autoprefixer

BROWSERSLIST='last 4 version' postcss -u autoprefixer --no-map
