#!/bin/bash

# http://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -o nounset -o errexit -o pipefail

# Remove prefixes from css
#
# usage
# $ cat a.css | ./css_autoprefixer_clean > out.css
#
# before begin
# $ npm install -g postcss-cli autoprefixer

# https://stackoverflow.com/a/39670269/1478566
BROWSERSLIST='>100%' postcss -u autoprefixer --no-map
