#!/bin/bash

# http://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -o nounset -o errexit -o pipefail

# POST as application/json with curl
# https://curl.haxx.se/docs/manpage.html

curl https://echo.vbarbarosh.com -H Content-Type:application/json
    -d '{"foo":1,"bar":2,"baz":[1,2,3]}'

curl https://echo.vbarbarosh.com -H Content-Type:application/json
    -d '@body.json'

# Note: Although `-d @body.json` https://curl.haxx.se/docs/manpage.html#-d
# will strip out all carriage returns and newlines it will not break
# json file. So, using this options is safe for sending json content.
