#!/bin/bash

# http://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -o nounset -o errexit -o pipefail

# A way to use curl in pipeline
# https://curl.haxx.se/docs/manpage.html

# Input from stdin, output to stdout
# https://curl.haxx.se/mail/archive-2002-01/0093.html

# Preferred way to send binary data
ls | curl https://echo.vbarbarosh.com --data-binary @- -o-

# More short option for sending json data from stdin
cat a.json | curl https://echo.vbarbarosh.com -d@- -o-

# Note: Although `-d @filename` https://curl.haxx.se/docs/manpage.html#-d
# will strip out all carriage returns and newlines it will not break
# json file. So, using this options is safe for sending json content.
