#!/bin/bash

# http://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -o nounset -o errexit -o pipefail

# Skip N first lines

# Skip 5 first lines
seq 10 | tail -n +6

# Skip 5 first lines
seq 10 | awk 'NR > 5'
