#!/bin/bash

# http://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -o nounset -o errexit -o pipefail

# Get N last lines

# Get last 10 lines
seq 100 | tail

# Get last 5 lines
seq 100 | tail -n5
